### ISSUE TITLE
Mencoder Error Message

### ISSUE THREAD

**Issue by hgn** [protocollabs/dmpr-simulator#20]
Not sure if real error. But after `make fast` the video encoding process looks something wired. Red/Yellow highlighted Could not open file, Could not find codec parameter ..`. Doesn't see this before.  
See the last line: `Output file #0 does not contain any stream`.

```
[image2 @ 0x55bf3bc8ff00] Could not open file : results/002-disappearing-node/images-range-tx-merge/*.png
[image2 @ 0x55bf3bc8ff00] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, image2, from 'results/002-disappearing-node/images-range-tx-merge/*.png':
  Duration: 00:00:00.10, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, none(pc), 10 tbr, 10 tbn, 10 tbc
Output #0, mp4, to 'results/002-disappearing-node/dmpr.mp4':
Output file #0 does not contain any stream
python3 dmpr-simulator 003-profile-core
```

**Comment by reisub-de** [comment]
Currently the simulator silently fails if he cannot import the dependencies for the image generation, I will add a warning and disable the ffmpeg call if that happens
