### ISSUE TITLE
Make Check Target

### ISSUE THREAD

**Issue by hgn** [protocollabs/dmpr-simulator#21]
Even if `make fast` is "fast" - it takes some time. Don't know yet but on my 6700K it takes over 30min. We probably should are a more lightweight test, called via `make check` that test all components and run all analyser somehow. Just to check that every component is fine. This target should be called from developer before every commit, to avoid un-executable tests.

**Comment by reisub-de** [comment]
Hmm, that is not so easy. I will add a check target which checks for dependencies and starts a really fast test run. See #23
