### ISSUE TITLE
Redesigned Image & Video Visualization

### ISSUE THREAD

**Issue by hgn** [protocollabs/dmpr-simulator#29]
# Introduction

As discussed the current visualization is not *that* modern. Replace it with a new design style

![untitled](https://user-images.githubusercontent.com/46653/31863630-49d7f8c2-b750-11e7-8de5-18e7db4f5152.png)

# New Prototype

I implemented a free-standing new version/style of the visualization, see the following link (moved to dmpr-simulation repo for now):

https://github.com/protocollabs/dmpr-simulator/blob/master/incubator/new-layout-grapher.py

Simple execute this script and see the "new style language". 

# New Features & and Background:

- draw **several path lines** between nodes. Previously there was one line, the thickness was increased if more paths where connected. This is technical fine but from visual view it looks a little bit awkward. Now we draw three lines if they are connected. Two if two is available and one direct line if only one path is available. And so on.
- Previously the image was splitted into two screens. The right screen reflected the same mesh structure but focused on visualization of DMPR packet transmission. Each **transmission** drawn a **red circle** for a static amount of time. This was fine. But using a separate screen makes no sense. The new visualization draws a small red arc around the circle. If the current prototype implementation is not *that* obvious we can make the circle later a bit thicker.
- Draw a more modern node **info rectangle**. Up until now just a number was drawn right next to the node. Now this version use something more modern like presented in this video: https://www.youtube.com/watch?v=BlRKJ3IWr1w 

# Missing Pieces

## From Full HD to 4K

The current prototype uses a 1000x1000 pixel area. This is not fine for video generation. If we can detach topology area and visualization area it will be great. E.g. a auto scaling feature or something like this. But I think this a way to much effort for little gain. So I think we should stick with a static pre-defined area for now and all the time. We can change/adjust the topology scenario to fit to the screen by using proper range parameter for the link technology (as done yet).

So the question boils down, if we use a static pre-defined pixel area for all scenarious, what is a proper size? We had FullHD for now. I suggest that we switch to **4k** now:  4,096 x 2160 pixel.

I hope the mencoder coding will not double or so. But anyway, I think the benefit for future is obviously. Furthermore, downconverting to FullHD is easy done later.

## Node Velocity vs. Routing Interval

In current/previous simulations the node velocity is quite high, unrealistic high. See the following video: https://www.youtube.com/watch?v=sI8tu9r2pIc&t=30s 
For people it seems that DMPR is a little bit slow to detect new routes. But this is not true: it takes at maximum hops*interval time to get a new route. E.g. so for a larger 5 network in a chain scenario it takes e.g. 5*30 seconds to propagate a route through the whole network. Which is quite fast. One the other hand, the movement/travel time to cross a network A->B->C is not a matter of seconds. Realistically it is more in the a *maximum* range of several minutes.

To sum up: the current node velocity speed is quite high. Which is good because it triggers often route changes. And it is the purpose of the simulator to stress test the protocol. On the other side for users it looks a little bit fast and that DMPR do not perform that well are converge fast.

To solve this we should make the **velocity** of nodes **configurable**. For protocol stress tests the velocity SHOULD be high. For presentation aspects the velocity of nodes should be reduced. At the video generation pass we can play with mplayer parameters and determine how many simulation seconds should be mapped to how many video seconds (e.g. 10 simulation seconds, one 1 video playback second)

## Node Movement

The bigger implementation task is the node movement characteristic. Now I statically draw a horizontal line. If node mode some additional calculation must place the proper corners based on relative positions and so on. This is the main burden of implementing the concept ... :cry:

**Comment by reisub-de** [comment]
yeah, this looks way nicer

**Comment by reisub-de** [comment]
> The current prototype uses a 1000x1000 pixel area. This is not fine for video generation. If we can detach topology area and visualization area it will be great. E.g. a auto scaling feature or something like this. But I think this a way to much effort for little gain. So I think we should stick with a static pre-defined area for now and all the time. We can change/adjust the topology scenario to fit to the screen by using proper range parameter for the link technology (as done yet).

Scaling is handled quite good by cairo itself, also centering if simulation area dimensions don't quite fit video dimensions. See:
https://github.com/protocollabs/dmpr-simulator/blob/da2b39868ecb6c864f423a631b4f46cccabb2b51/dmprsim/simulator/draw.py#L349-L359

> In current/previous simulations the node velocity is quite high, unrealistic high. See the following video: https://www.youtube.com/watch?v=sI8tu9r2pIc&t=30s

This is a really old video, in new versions of the simulator the speed is already much lower and configurable, defaults to `random()**6`

> The bigger implementation task is the node movement characteristic. Now I statically draw a horizontal line. If node mode some additional calculation must place the proper corners based on relative positions and so on.

What about https://pycairo.readthedocs.io/en/latest/reference/context.html#cairo.Context.curve_to ?
This would be a bit easier to draw and should give a fluid movement of the whole curve while the node is moving.
